[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: UI tests
    smoke: Smoke tests
    slow: Slow tests
    critical: Critical tests
    regression: Regression suite
    positive: Positive scenarios
    negative: Negative scenarios
    registration: Registration tests
    authorization: Authorization tests
    courses: Courses tests
    dashboard: Dashboard tests